<a href="https://colab.research.google.com/github/temple17/python-for-data-analysis-2nd-edition/blob/main/Chapter5%20(p_141~186).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from pandas import Series, DataFrame

In [ ]:
# Series
obj = pd.Series([4,7,-5,3])

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [ ]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6

In [ ]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
'b' in obj2

True

In [ ]:
'e' in obj2

False

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
obj3 = pd.Series(sdata)

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California','Ohio','Oregon','Texas']

In [ ]:
obj4 = pd.Series(sdata, index=states)

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'

In [ ]:
obj4.index.name = 'state'

In [ ]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [ ]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [ ]:
# Dataframe

data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop': [1.5, 1.7, 3.6,2.4,2.9,3.2]}

In [ ]:
frame = pd.DataFrame(data)

In [ ]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'],
                      index = ['one','two','three','four','five','six'])

In [ ]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2.loc[['three']]

year state  pop debt
three  2002  Ohio  3.6  NaN

In [ ]:
frame2['debt'] = 16.5

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [ ]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])

In [ ]:
frame2['debt'] = val

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio'

In [ ]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [ ]:
del frame2['eastern']

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001:2.4, 2002: 2.9},
       'Ohio': {2000:1.5, 2001: 1.7, 2002: 3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)

In [ ]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [ ]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
obj = pd.Series(range(3), index = ['a','b','c'])

In [ ]:
index = obj.index

In [ ]:
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
obj

a    0
b    1
c    2
dtype: int64

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
import numpy as np

In [ ]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)

In [ ]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.index

False

In [ ]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 5.2 Essential Functionality

obj = pd.Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])

In [ ]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [ ]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3= pd.Series(['blue','purple','yellow'], index = [0,2,4])

In [ ]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a','c','d',],
                     columns = ['Ohio','Texas','California'])

In [ ]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])

In [ ]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
states = ['Texas','Utah','California']

In [ ]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])

In [3]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [4]:
new_obj = obj.drop('c')

In [5]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [6]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [7]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [8]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])

In [9]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [12]:
data.drop(['two','four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [13]:
obj.drop('c', inplace = True)

In [14]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [15]:
# indexing, selection, and filtering

obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [16]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [17]:
obj['b']

1.0

In [18]:
obj[1]

1.0

In [19]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [20]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [21]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [22]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [23]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [24]:
obj['b':'c'] = 5

In [25]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [26]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])

In [27]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [29]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [36]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [31]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [38]:
data[data < 5] = 0

In [39]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
# selection and loc and iloc

data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [42]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [43]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [44]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [45]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [46]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [47]:
# integer indexes

ser = pd.Series(np.arange(3.))

In [48]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [50]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])

In [51]:
ser2[-1]

2.0

In [52]:
ser[:1]

0    0.0
dtype: float64

In [53]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [54]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [55]:
ser.iloc[:1]

0    0.0
dtype: float64

In [56]:
# arithmetic and data alignment

s1 = pd.Series([7.3,-2.5,3.4,1.5], index = ['a','c','d','e'])

In [58]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
               index = ['a','c','e','f','g'])

In [59]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [60]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [61]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [62]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'),
                   index = ['Ohio','Texas','Colorado'])

In [63]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                   index = ['Utah', 'Ohio','Texas','Oregon'])

In [64]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [65]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [66]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [67]:
df1 = pd.DataFrame({'A': [1,2]})

In [69]:
df2 = pd.DataFrame({'B': [3,4]})

In [70]:
df1

A
0  1
1  2

In [71]:
df2

B
0  3
1  4

In [72]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [73]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list('abcd'))

In [74]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns = list('abcde'))

In [75]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [76]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [77]:
df2.loc[1, 'b'] = np.nan

In [78]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [79]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [80]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [81]:
1 /df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [82]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [83]:
df1.reindex(columns = df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [84]:
arr = np.arange(12.).reshape((3,4))

In [85]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [86]:
arr[0]

array([0., 1., 2., 3.])

In [87]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [88]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])

In [89]:
series = frame.iloc[0]

In [90]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [91]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [92]:
frame- series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [93]:
series2 = pd.Series(range(3), index = ['b','e','f'])

In [94]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [95]:
series2

b    0
e    1
f    2
dtype: int64

In [96]:
series3 = frame['d']

In [97]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [98]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [100]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [107]:
# function application and mapping

frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])

In [108]:
frame

b         d         e
Utah    1.517636 -1.143710  1.491994
Ohio   -1.538115 -0.929598 -0.753290
Texas  -0.684806  0.333267 -0.065251
Oregon -1.521369  0.691945 -1.547826

In [109]:
np.abs(frame)

b         d         e
Utah    1.517636  1.143710  1.491994
Ohio    1.538115  0.929598  0.753290
Texas   0.684806  0.333267  0.065251
Oregon  1.521369  0.691945  1.547826

In [110]:
f = lambda x: x.max() - x.min()

In [111]:
frame.apply(f)

b    3.055752
d    1.835655
e    3.039820
dtype: float64

In [112]:
frame.apply(f, axis = 'columns')

Utah      2.661346
Ohio      0.784825
Texas     1.018073
Oregon    2.239771
dtype: float64

In [113]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [114]:
frame.apply(f)

b         d         e
min -1.538115 -1.143710 -1.547826
max  1.517636  0.691945  1.491994

In [115]:
format = lambda x: '%.2f' % x

In [117]:
frame.applymap(format)

b      d      e
Utah     1.52  -1.14   1.49
Ohio    -1.54  -0.93  -0.75
Texas   -0.68   0.33  -0.07
Oregon  -1.52   0.69  -1.55

In [118]:
frame['e'].map(format)

Utah       1.49
Ohio      -0.75
Texas     -0.07
Oregon    -1.55
Name: e, dtype: object

In [119]:
# sorting and ranking
obj = pd.Series(range(4), index = ['d','a','b','c'])

In [120]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [121]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index = ['three','one'],
                     columns = ['d','a','b','c'])

In [122]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [123]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [124]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [125]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [126]:
obj = pd.Series([4,7,-3,2])

In [127]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [128]:
obj = pd.Series([4,np.nan, 7, np.nan, -3,2])

In [129]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [130]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [131]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [132]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [133]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [134]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [135]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [136]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [137]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [138]:
# Assign tie values the maximum rank in the group
obj.rank(ascending= False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [139]:
frame = pd.DataFrame({'b': [4.3,7,-3,2], 'a': [0,1,0,1],
                      'c': [-2,5,8,-2.5]})

In [140]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [141]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [142]:
# axis indexes with duplicate labels

obj = pd.Series(range(5), index = ['a','a','b','b','c'])

In [143]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [144]:
obj.index.is_unique

False

In [145]:
obj['a']

a    0
a    1
dtype: int64

In [146]:
obj['c']

4

In [147]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])

In [148]:
df

0         1         2
a -0.843681  0.454502  0.927512
a -1.014359  0.447407  0.401267
b -0.625096  0.455361  0.961666
b  0.915296 -0.444422  0.812531

In [149]:
df.loc['b']

0         1         2
b -0.625096  0.455361  0.961666
b  0.915296 -0.444422  0.812531

In [150]:
# summarizing and computing descriptive statistics

df = pd.DataFrame([[1.4, np.nan], [7.1,-4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index = ['a','b','c','d'],
                  columns = ['one','two'])

In [151]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [152]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [153]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [154]:
df.mean(axis = 'columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [155]:
df.idxmax()

one    b
two    d
dtype: object

In [156]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [157]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [158]:
obj = pd.Series(['a','a','b','c'] * 4)

In [162]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [163]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [164]:
uniques = obj.unique()

In [165]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [166]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [167]:
pd.value_counts(obj.values, sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [168]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [169]:
mask = obj.isin(['b','c'])

In [170]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [171]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [172]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [173]:
unique_vals = pd.Series(['c','b','a'])

In [174]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [175]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
                     'Qu2': [2,3,1,2,3],
                     'Qu3': [1,5,2,4,4]})

In [176]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [177]:
result = data.apply(pd.value_counts).fillna(0)

In [178]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0